services:
  # -----------------------------------------------------------------
  # Servicio de Base de Datos (Data Warehouse)
  # -----------------------------------------------------------------
  db:
    image: postgres:16
    container_name: chinook_db
    environment:
      POSTGRES_USER: devlights_user
      POSTGRES_PASSWORD: devlights_password
      POSTGRES_DB: chinook
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Scripts de carga inicial (OLTP y OLAP)
      - ./assets/01_oltp.sql:/docker-entrypoint-initdb.d/01_oltp.sql
      - ./assets/02_olap.sql:/docker-entrypoint-initdb.d/02_olap.sql
    networks:
      - chinook_net
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devlights_user -d chinook"]
      interval: 10s
      timeout: 5s
      retries: 5

  # -----------------------------------------------------------------
  # Servicio de Visualización (Metabase con Dashboards Precargados)
  # -----------------------------------------------------------------
  metabase:
    image: metabase/metabase:latest
    container_name: chinook_bi
    volumes:
      - ./metabase_backup_data:/metabase-data
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    networks:
      - chinook_net 
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  # -----------------------------------------------------------------
  # Servicio de Administración de BD (pgAdmin 4)
  # -----------------------------------------------------------------
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: chinook_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@chinook.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - chinook_net
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  chinook_net:
    driver: bridge